apiVersion: v1
kind: Service
metadata:
  name: aks-test-2
  namespace: aks-test-app-namespace
spec:
  type: LoadBalancer
  selector:
    app: aks-test-2
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
